config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'about', to: 'home#about', as: 'about'

  resource :business, only: %i(show new create)
  resource :config, only: %i(show update) do
    resource :business, only: %i(update)
    resources :fields, only: %i(new create edit destroy)
    resources :portfolios, only: %i(update create)
    resources :users, only: %i(update create)
  end
  resources :events, only: %i(index)
  resources :portfolios, only: %i(show)
  resources :securities, only: %i(create show) do
    resources :prices, only: %i(index)
  end
  resources :trades, only: %i(new create edit update)
  resource :user_setup, only: %i(new create) do
    collection do
      get :business
      get :portfolio
    end
  end
  resource :yahoo_security_search, only: %i(show create)

  # custom error pages
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  def show
    @tab = params[:tab] || view_context.config_tab_options.keys.first
    @business = current_user.business
  end

  def update
    updater = ConfigUpdater.new(params, current_user)
    if updater.update
      flash[:info] = 'Successfully updated config'
      redirect_to config_path
    else
      flash[:danger] = 'Error updated config'
      @errors = updater.errors
      @business = current_user.business
      render :show
    end
  end
end

app/views/configs/_business.html.slim
= form_for @business || current_user.business, url: config_business_path do |f|
  .row
    .col-lg-6
      .row
        .col-md-8
          = field(f, field_name: :name) do
            = f.label :name
            = f.text_field :name, class: 'form-control t-business-name'

    .col-lg-6
      = field(f, field_name: :reporting_currency) do
      = f.label :reporting_currency
      = f.select :reporting_currency, %w(AUD USD), { include_blank: true }, class: "form-control t-reporting-currency"

  .row
    .form_group.col-md-12
      = f.submit 'Update', class: 'btn btn-primary t-save'

app/views/configs/_custom_fields.html.slim
.col-md-12
  .table-responsive
    table.table.table-striped
      thead
        tr
          th style='width: 80px'
          th Name
          th Default
          th Type
          th Validations
      tbody
        - custom_config.config.each do |key, details|
          tr.t-field
            td
              = link_to config_field_path(id: custom_config.id, key: key), method: :delete, 'data-confirm' => 'Are you sure you want to delete this field?', class: 't-delete' do
                i.fa.fa-trash.fa-lg.warning  title='Delete'
              '  |
              = link_to edit_config_field_path(id: custom_config.id, key: key), class: 't-edit' do
                i.fa.fa-edit.fa-lg title='Edit'
            td.t-field-name= details['name']
            td= details['default']
            td= (details['type'] || '').humanize
            td= details['validations'] && details['validations'].keys.to_sentence.humanize

app/views/configs/_fields.html.slim
= fields_for :config, config do |f|
  - config.each do |field|
    .col-lg-6
      = render "configs/field_types/#{CustomConfig::CONFIG_OPTIONS[field.to_sym][:type]}", f: f, key: field

app/views/configs/_portfolio.html.slim
= fields_for :portfolio, portfolio, index: portfolio.id do |p|
  .config-group
    h2
      ' Portfolio:
      = portfolio.name

    .row
      .form_group.col-md-4
        = p.label :name, 'Portfolio name'
        = p.text_field :name, class: 'form-control'

app/views/configs/_portfolios.html.slim
- Portfolio.where(business: current_user.business).each do |portfolio|
  .config-group.t-portfolio id="portfolio-#{portfolio.id}"
    - current_portfolio = @portfolio&.id == portfolio.id ? @portfolio : portfolio
    = form_for current_portfolio, url: config_portfolio_path(current_portfolio, anchor: "portfolio-#{current_portfolio.id}") do |f|
      .row
        .col-lg-12
          h3= current_portfolio.name
      .row
        .col-md-6
          = field(f, field_name: :name) do
            = f.label :name
            = f.text_field :name, class: 'form-control t-portfolio-name'

      .row
        = render 'configs/fields', config: (@portfolio&.id == portfolio.id ? @config : config_for(current_portfolio)).config_instance

      .row
        .col-md-12
          .form_group
            = f.submit 'Update', class: 'btn btn-primary t-save'

      .row
        .col-md-12
          h3 Trade fields
        = render 'configs/custom_fields', custom_config: config_for(portfolio, config_type: CustomConfig::TRADE_FIELDS)
        .col-md-12
          h3 Backoffice fields
        = render 'configs/custom_fields', custom_config: config_for(portfolio, config_type: CustomConfig::BACKOFFICE_FIELDS)

      .row
        .form_group.col-md-12
          = link_to 'Add field', new_config_field_path(owner_type: 'Portfolio', owner_id: current_portfolio), class: 'btn btn-info t-add-field-config'

config-group
  .row
    .col-md-12
      - portfolio = @new_portfolio || Portfolio.new
      = form_for portfolio, url: config_portfolios_path(anchor: 'new_portfolio') do |f|
        h1 New Portfolio
        .row
          .col-md-6
            = field(f, field_name: :name, hint: 'Portfolios group similar trades together.')
              = f.label :name, 'Portfolio name'
              = f.text_field :name, class: 't-new-portfolio-name form-control'

        .row
          .col-md-6
            = field_tag(value: nil, hint: 'Select an existing portfolio to base the configuration off.')
              = f.label :configuration, 'Base Configuration'
              = select_tag :configuration, options_for_select(copy_portfolio_config_options), required: true, class: 'form-control'

        .form_group
          = f.submit 'Create', class: 'btn btn-primary t-add'

app/views/configs/_user.html.slim
.row
  .col-lg-6
    = form_for @user || current_user, url: config_user_path(@user || current_user) do |f|
      .row
        .col-md-8
          = field(f, field_name: :name) do
            = f.label :name
            = f.text_field :name, class: 'form-control t-user-name'

      .row
        .col-md-12
          .form_group
            = f.submit 'Update', class: 'btn btn-primary t-save'

    - user_creator = @user_creator || UserCreator.new(current_user: current_user, role_id: (@user || current_user).role_id)
    = form_for user_creator, url: config_users_path(anchor: 'new_user_creator') do |f|
      h2 Add user(s)
      .row
        .col-md-12
          = field(f, field_name: :emails, hint: 'comma separated list of user emails to be created') do
            = f.label :emails, 'Email(s)'
            = f.text_field :emails, placeholder: 'bob@new-user.com, jack@new-user.com', class: 'form-control input-normal t-emails'

      .row
        .col-md-6
          = field(f, field_name: :role_id) do
            = f.label :role_id, 'Role'
            = f.collection_select :role_id, Role.settable_for_user(current_user), :id, :pretty_name, {}, class: 'form-control input-normal'

      .row
        .col-md-12
          .form_group
            = submit_tag 'Add', class: 'btn btn-primary t-add'

  .col-lg-6
    h2 Users

    .table-responsive
      table.table.table-hover
        thead
          tr
            th Name
            th Email
            th Role
            th Last Access
        tbody
          - User.where(business: current_user.business).each do |user|
            tr
              td= user.name
              td= user.email
              td= user.role.pretty_name
              td= user.uid ? user.updated_at.to_s(:short) : 'Never'

app/views/configs/show.html.slim
.row
  .col-md-12
    h1 Config

.row
  .col-md-12
    ul.nav.nav-tabs role="tablist"
      - config_tab_options.each do |id, name|
        li.nav-item
          a.nav-link.t-tab href=config_path(tab: id) class=(@tab == id ? 'active' : '')
            = name

.row
  .col-md-12
    .tab-content
      tab-pane.portfolio-tab.active role="tabpanel"
        = render "configs/#{@tab}"