config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'about', to: 'home#about', as: 'about'

  resource :business, only: %i(show new create)
  resource :config, only: %i(show update) do
    resource :business, only: %i(update)
    resources :fields, only: %i(new create edit destroy)
    resources :portfolios, only: %i(update create)
    resources :users, only: %i(update create)
  end
  resources :events, only: %i(index)
  resources :portfolios, only: %i(show)
  resources :securities, only: %i(create show) do
    resources :prices, only: %i(index)
  end
  resources :trades, only: %i(new create edit update)
  resource :user_setup, only: %i(new create) do
    collection do
      get :business
      get :portfolio
    end
  end
  resource :yahoo_security_search, only: %i(show create)

  # custom error pages
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :business
  has_many :trades
  default_scope { where(current: true) }

  validates :name, presence: true
  validates :name, uniqueness: { scope: [:business, :current] }, if: :current?
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def show
    @portfolio = policy_scope(Portfolio).find(params[:id])
  end

  def create
    authorize Portfolio
    @new_portfolio = Portfolio.new(portfolio_params.merge(business: current_user.business, uid: SecureRandom.uuid))

    if save_with_events(@new_portfolio, config_for(@new_portfolio, clone_id: params[:configuration]))
      redirect_to config_path(tab: :portfolios, anchor: "portfolio-#{@new_portfolio.id}")
    else
      @tab = 'portfolios'
      render 'configs/show'
    end
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    authorize @portfolio
    @portfolio.assign_attributes(portfolio_params)
    @config = config_for(@portfolio, params: config_params(@portfolio))
    if save_with_events(@portfolio, @config)
      redirect_to config_path(tab: :portfolios, anchor: "portfolio-#{@portfolio.id}")
    else
      @tab = 'portfolios'
      render 'configs/show'
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:name)
  end

  def config_params(portfolio)
    params.require(:config).permit(CustomConfig.defaults(portfolio).keys)
  end
end

app/views/portfolios/_portfolio.html.slim
.row
  .col-md-12
    h1
      ' Portfolio:
      = portfolio.name


- tab = params[:tab] || 'trades'
.row
  .col-md-12
    ul.nav.nav-tabs role="tablist"
      li.nav-item.t-pending-trades
        a.nav-link class=('active' if tab == 'trades') href=portfolio_path(portfolio, tab: 'trades')
          .portfolio-stat__description Pending trades:&nbsp;
          .portfolio-stat__number = portfolio.trades.current.unsettled.count
      li.nav-item
        a.nav-link class=('active' if tab == 'positions') href=portfolio_path(portfolio, tab: 'positions')
          .portfolio-stat__description Positions:&nbsp;
          .portfolio-stat__number = portfolio.trades.current.group(:security_id).having('sum(quantity) != 0').count.count
      li.nav-item
        a.nav-link class=('active' if tab == 'valuations') href=portfolio_path(portfolio, tab: 'valuations')
          .portfolio-stat__description Valuation:&nbsp;
          .portfolio-stat__number = number_to_currency portfolio.trades.current.sum('quantity * price')


.row
  .col-md-12
    .tab-content
      tab-pane.portfolio-tab.active role="tabpanel"
        = render "portfolios/#{tab}", portfolio: portfolio

app/views/portfolios/_positions.html.slim
#positions.tab-pane.portfolio-tab.fade.in.active role="tabpanel"

  .table-responsive
    table.table.table-striped.table-hover
      thead
        tr
          th Symbol
          th Quantity
          th Description
          th Book Cost
          th Bid
          th Offer
          th Change
          th Market Value
          th Gain/Loss
          th Open
          th High
          th Low
      tbody
        - positions = portfolio.trades.includes(security: :today_price).group(:security_id).select(:security_id, 'sum(quantity) quantity')
        - positions.sort_by { |p| p.security.name }.each do |trade|
          tr.t-trade
            td= link_to trade.security.ticker, security_path(trade.security_id)
            td.right-align= number_with_delimiter(trade.quantity)
            td= trade.security.name
            th
            th
            th
            th
            th.right-align= number_to_currency(trade.security.today_price.close * trade.quantity, unit: trade.security.currency) if trade.security.today_price
            th
            th.right-align= number_to_currency(trade.security.today_price&.open)
            th.right-align= number_to_currency(trade.security.today_price&.high)
            th.right-align= number_to_currency(trade.security.today_price&.low)

app/views/portfolios/_trades.html.slim
#trades.tab-pane.portfolio-tab.fade.in.active role="tabpanel"
  h2 Pending

  .table-responsive
    table.table.table-striped.table-hover
      thead
        tr
          th UID
          th Trade Date
          th Direction
          th Quantity
          th Price
          th CCY
          th Cost
          th Security
      tbody
        - portfolio.trades.current.unsettled.includes(:security).each do |trade|
          tr.t-trade
            td= link_to trade.uid, edit_trade_path(trade.uid), class: 't-trade-uid'
            td= trade.date.to_s(:short)
            td= trade.quantity.positive? ? 'Buy' : 'Sell'
            td= trade.quantity.abs
            td= number_to_currency trade.price
            td= trade.currency
            td= number_to_currency (trade.price * trade.quantity).abs
            td= trade.security.name

app/views/portfolios/_valuations.html.slim
#valuation.tab-pane.portfolio-tab.fade role="tabpanel"
  | Pending

app/views/portfolios/show.html.slim
.row
  .col-md-12
    a.btn.btn-primary.t-book-trade href=new_trade_path(trade: { portfolio_id: @portfolio.id }) New trade

= render 'portfolio', portfolio: @portfolio