config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'about', to: 'home#about', as: 'about'

  resource :business, only: %i(show new create)
  resource :config, only: %i(show update) do
    resource :business, only: %i(update)
    resources :fields, only: %i(new create edit destroy)
    resources :portfolios, only: %i(update create)
    resources :users, only: %i(update create)
  end
  resources :events, only: %i(index)
  resources :portfolios, only: %i(show)
  resources :securities, only: %i(create show) do
    resources :prices, only: %i(index)
  end
  resources :trades, only: %i(new create edit update)
  resource :user_setup, only: %i(new create) do
    collection do
      get :business
      get :portfolio
    end
  end
  resource :yahoo_security_search, only: %i(show create)

  # custom error pages
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  def new
    @field = FieldForm.new(config_params)
    authorize @field
  end

  def create
    @field = FieldForm.new(field_params)
    authorize @field
    if @field.valid?
      custom_config_for_editing(portfolio, @field.config_type) do |config|
        config.merge!(@field.as_json)
      end
      redirect_to config_path(tab: 'portfolios', anchor: "portfolio-#{portfolio.id}")
    else
      render :new
    end
  end

  def edit
    authorize_change?
    render :new
  end

  def destroy
    authorize_change?
    base_custom_config = CustomConfig.find(params[:id])
    key = params.fetch(:key)
    if base_custom_config.config.key?(key)
      custom_config_for_editing(base_custom_config.owner, base_custom_config.config_type) do |config|
        config.delete(key)
      end
    end
    redirect_to config_path(tab: 'portfolios')
  end

  private

  def authorize_change?
    custom_config = CustomConfig.find(params[:id])
    key = params.fetch(:key)
    @field = FieldForm.new(custom_config.config.fetch(key).merge(config_type: custom_config.config_type))
    authorize @field
  end

  def config_params
    hash = params[:field_form] || params
    {
      owner_id: hash.fetch(:owner_id),
      owner_type: hash.fetch(:owner_type),
      config_type: CustomConfig::TRADE_FIELDS,
    }
  end

  def field_params # rubocop:disable Metrics/MethodLength
    params
      .require(:field_form)
      .permit(
        :owner_id,
        :owner_type,
        :config_type,
        :name,
        :type,
        :values,
        :default,
        :validates_presence,
        :validates_inclusion,
      )
  end

  def custom_config_for_editing(portfolio, config_type)
    new_portfolio = portfolio.trades.any? ? clone_portfolio(portfolio) : portfolio

    custom_config = custom_config(new_portfolio, config_type)
    custom_config.config ||= {}
    yield custom_config.config
    save_with_events(custom_config)
  end

  def custom_config(portfolio, config_type)
    CustomConfig.find_or_initialize_by(
      owner_id: portfolio.id,
      owner_type: 'Portfolio',
      config_type: config_type,
    )
  end

  def portfolio
    @portfolio ||= Portfolio.find(config_params[:owner_id])
  end

  def clone_portfolio(portfolio)
    new_portfolio = portfolio.dup
    new_portfolio.version += 1
    portfolio.update!(current: false)
    new_portfolio.save!

    CustomConfig.where(owner_id: portfolio.id, owner_type: 'Portfolio').each do |config|
      new_config = config.dup
      new_config.owner_id = new_portfolio.id
      new_config.save!
    end
    new_portfolio
  end
end

app/views/fields/new.html.slim
.row
  .col-md-12
    h1 New Field

.row
  .col-lg-6
    = form_for @field, as: :field_form, url: config_fields_path do |f|
      = f.hidden_field :owner_id
      = f.hidden_field :owner_type

      .row
        .col-md-12
          = field(f, field_name: :config_type) do
            h3 Field for

            .form_control
              .form-check.form-check-inline
                label.form-check-label
                  = f.radio_button :config_type, CustomConfig::TRADE_FIELDS, class: 'form-check-input t-config-type'
                  '  Trade adjustment
              .form-check.form-check-inline
                label.form-check-label
                  = f.radio_button :config_type, CustomConfig::BACKOFFICE_FIELDS, class: 'form-check-input t-config-type'
                  '  Trade tracking/settlement

      .row
        .col-md-8.col-xl-6
          = field(f, field_name: :name) do
            = f.label :name
            = f.text_field :name, class: 't-name form-control'

      .row
        .col-md-8.col-xl-6
          = field(f, field_name: :deafult) do
            = f.label :default
            = f.text_field :default, class: 't-default form-control'

      .row
        .col-md-12
          = field(f, field_name: :type) do
            h3 Field Type

            .form_control
              .form-check.form-check-inline
                label.form-check-label
                  = f.radio_button :type, :string, class: 'form-check-input t-type'
                  '  Text
              .form-check.form-check-inline
                label.form-check-label
                  = f.radio_button :type, :number, class: 'form-check-input t-type'
                  '  Number
              .form-check.form-check-inline
                label.form-check-label
                  = f.radio_button :type, :list, class: 'form-check-input t-type'
                  '  Lookup

      .row
        .col-md-8.col-xl-6
          = field(f, field_name: :values) do
            = f.label :values
            = f.text_field :values, class: 't-values form-control'
      .row
        .col-md-8.col-xl-6
          = field(f, field_name: :name) do
            h3 Validations
            .form-check
              label.form-check-label
                = f.check_box :validates_presence, class: 't-validates-presence form-check-input'
                | Required field

            .form-check
              label.form-check-label
                = f.check_box :validates_inclusion, class: 't-validates-inclusion form-check-input'
                | Must be element from list

      .row
        .col-md-4
          .form-group
            = f.submit 'Save', class: 'btn btn-primary t-save-button'